include: package:very_good_analysis/analysis_options.3.1.0.yaml
linter:
  rules:
    public_member_api_docs: false
    # sort_pub_dependencies: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - lib/injector.config.dart
    - lib/env_config.dart
  errors:
    invalid_annotation_target: ignore
